server:
  port: 8001
spring:
  application:
    name: health_admin
  datasource:
    url: jdbc:mysql://localhost:3306/health?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: mynewpassword
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8888/xxl-job-admin
    executor:
      appname: xxl-job-executor-sample
      port: 9999


minio:
  accessKey: minio
  secretKey: minio123
  bucket: health
  endpoint: http://192.168.200.131:9000
  readPath: http://192.168.200.131:9000