server:
  port: 8001
spring:
  application:
    name: health_admin
  datasource:
    url: jdbc:mysql://localhost:3306/health?serverTimezone=Asia/Shanghai/useSSL=false
    username: root
    password: Science
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

minio:
  host: http://127.0.0.1:9000/
  bucket: health
